spring.application.name=profile-service

server.port=8052

eureka.client.service-url.defaultZone=http://localhost:8050/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/cinebook_profiledb
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=CineBookSecretKey2024ForJWTTokenGenerationAndValidation
jwt.expiration=86400000